spring.application.name=subastaya

spring.datasource.url=jdbc:postgresql://localhost:5432/subastaya
spring.datasource.username=subastaya
spring.datasource.password=subastaya

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true